server:
  # HTTP服务配置
  http:
    port: 8080
    read_timeout: 5s
    write_timeout: 10s
    idle_timeout: 15s
    max_response_size: 10485760  # 10MB

  # 限流配置
  rate_limit:
    requests_per_second: 100
    burst_size: 200

# Kafka配置
kafka:
  brokers:
    - "localhost:9092"
  producer:
    compression: "snappy"
    message_timeout: 3000
    retries: 3
    acks: "all"
  consumer:
    group_id: "ollama-search"
    auto_offset_reset: "latest"

# 搜索配置
search:
  endpoint: "http://localhost:8080/search"
  timeout: 10s
  topic: "search_results"

# HTTP客户端配置
client:
  timeout: 10s
  max_idle_conns: 100
  max_idle_conns_per_host: 20
  idle_conn_timeout: 30s

# 日志配置
logging:
  format: "[%s] %s %d %s %s"
  include:
    - method
    - path
    - status_code
    - duration
    - user_agent
